import { notFound } from 'next/navigation';
import dbConnect from '@/lib/db';
import Job from '@/models/Job';
import User from '@/models/User';
import JobOutputTabs from '@/components/JobOutputTabs';
import Workspace from '@/models/Workspace';
import { ExternalLink } from 'lucide-react';
import Link from 'next/link';
import { Metadata } from 'next';

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
    const { slug } = await params;
    await dbConnect();
    const job = await Job.findOne({ shareSlug: slug, isPublic: true }).lean();

    if (!job) {
        return { title: 'Not Found | Content Repurposer' };
    }

    const jobTitle = job.title || 'Repurposed Video Content';
    return {
        title: `${jobTitle} | Content Repurposer`,
        description: 'See this AI-repurposed social media content generated by Content Repurposer.',
    };
}

export default async function PublicSharePage({ params }: { params: Promise<{ slug: string }> }) {
    const { slug } = await params;
    await dbConnect();

    const job = await Job.findOne({ shareSlug: slug, isPublic: true }).lean();
    if (!job) notFound();

    // Determine if we need to watermark based on the creator's plan
    const creator = await User.findOne({ clerkId: job.userId }).lean();
    const isWatermarked = !creator || creator.plan === 'free';

    const workspace = await Workspace.findOne({
        $or: [{ ownerId: job.userId }, { memberIds: job.userId }]
    }).lean();

    const branding = (workspace as any)?.branding;

    return (
        <div className="container mx-auto px-4 py-8 max-w-4xl min-h-screen flex flex-col">
            {branding?.logo && (
                <div className="mb-8 flex justify-center sm:justify-start">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={branding.logo} alt="Agency Logo" className="h-12 object-contain" />
                </div>
            )}

            <div className="flex-1">
                <div className="mb-6 space-y-2">
                    {!branding?.logo && <h1 className="text-3xl font-bold">Repurposed Content</h1>}
                    <div className="flex items-center gap-2 text-muted-foreground text-sm">
                        <span>Source:</span>
                        <a href={job.inputUrl as string} target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline flex items-center gap-0.5">
                            {job.inputUrl as string}
                            <ExternalLink className="w-3 h-3" />
                        </a>
                    </div>
                </div>

                <div className="bg-card border rounded-xl overflow-hidden shadow-sm">
                    <div className="p-4 sm:p-6">
                        <JobOutputTabs
                            outputs={job.outputs as any}
                            jobId={job._id.toString()}
                            watermark={isWatermarked}
                        />
                    </div>
                </div>
            </div>

            {/* Virality / Growth Footer */}
            {isWatermarked && (
                <div className="mt-12 py-8 text-center text-sm border-t border-border/50">
                    <p className="text-muted-foreground mb-3">
                        This content was generated 10x faster with AI.
                    </p>
                    <Link href="/" className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2">
                        Try Content Repurposer for Free
                    </Link>
                </div>
            )}
        </div>
    );
}
